apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: coursemanagementapi
    version: "1.0"
  name: coursemanagementapi
  namespace: student-management-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coursemanagementapi
      version: "1.0"
  template:
    metadata:
      labels:
        app: coursemanagementapi
        version: "1.0"
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        image: student-management-system/coursemanagementapi:1.0
        imagePullPolicy: IfNotPresent
        name: coursemanagementapi
        ports:
        - containerPort: 5000
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: coursemanagementapi
  name: coursemanagementapi
  namespace: student-management-system
spec:
  type: NodePort
  ports:
  - name: "http-5000"
    port: 5000
    targetPort: 5000
    nodePort: 30006
  selector:
    app: coursemanagementapi

