apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: enrollmentmanagementapi
    version: "1.0"
  name: enrollmentmanagementapi
  namespace: student-management-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enrollmentmanagementapi
      version: "1.0"
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: enrollmentmanagementapi
        version: "1.0"
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        image: student-management-system/enrollmentmanagementapi:1.0
        imagePullPolicy: IfNotPresent
        name: enrollmentmanagementapi
        ports:
        - containerPort: 5200
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: enrollmentmanagementapi
  name: enrollmentmanagementapi
  namespace: student-management-system
spec:
  ports:
  - name: http-5200
    nodePort: 30007
    port: 5200
    targetPort: 5200
  selector:
    app: enrollmentmanagementapi
  type: NodePort
---
