apiVersion: v1
kind: ConfigMap
metadata:
  name: rqconfigmap
  namespace: student-management-system
data:
  rabbitmq.conf: |
    default_user = rabbitmquser
    default_pass = DEBmbwkSrzy9D1T9cJfa

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rabbitmq
    version: v1
  name: rabbitmq
  namespace: student-management-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - env:
        - name: RABBITMQ_CONFIG_FILE
          value: /etc/student-management-system/rabbitmq.conf
        image: rabbitmq:3-management-alpine
        imagePullPolicy: IfNotPresent
        name: rabbitmq
        ports:
        - containerPort: 15672
        - containerPort: 5672
        volumeMounts:
        - name: rqconfig
          mountPath: "/etc/student-management-system"
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: rqconfig
        configMap:
          name: rqconfigmap

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
  namespace: student-management-system
spec:
  type: NodePort
  ports:
  - name: "http-admin"
    port: 15672
    targetPort: 15672
    nodePort: 30001
  - name: "data"
    port: 5672
    targetPort: 5672
  selector:
    app: rabbitmq
